package com.training;
// Generated Nov 25, 2015 2:41:38 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Writer generated by hbm2java
 */
public class Writer implements java.io.Serializable {

	private int writerId;
	private Set<Story> stories = new HashSet<Story>(0);
	private String writerName;

	public Writer() {
	}

	public Writer(Set<Story> stories, String writerName) {
		this.stories = stories;
		this.writerName = writerName;
	}

	public Writer(String writerName) {
		this.writerName = writerName;	}

	public int getWriterId() {
		return this.writerId;
	}

	public void setWriterId(int writerId) {
		this.writerId = writerId;
	}

	public Set<Story> getStories() {
		return this.stories;
	}

	public void setStories(Set<Story> stories) {
		this.stories = stories;
	}

	public String getWriterName() {
		return this.writerName;
	}

	public void setWriterName(String writerName) {
		this.writerName = writerName;
	}

}
